import { PUBLIC_STELLAR_RPC_URL, PUBLIC_STELLAR_NETWORK_PASSPHRASE } from '$env/static/public';

export const RPC_URL = PUBLIC_STELLAR_RPC_URL;
export const NETWORK_PASSPHRASE = PUBLIC_STELLAR_NETWORK_PASSPHRASE;
